# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmQMQksT_EO8l7JmW2atqi3MCrSFS8qK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

x=[1,2,3,4,5]
y=[2,3,5,5,8]

data={'X':x,'Y':y}

df=pd.DataFrame(data)

print(df)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df.X,df.Y)
plt.xlabel('Ad Spend')
plt.ylabel('Sales')

reg=linear_model.LinearRegression()
reg.fit(df[['X']],df.Y)

reg.coef_

reg.intercept_

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df.X,df.Y,color='red',marker='+')
plt.xlabel('Study hours')
plt.ylabel('Mark')
plt.plot(df.X,reg.predict(df[['X']]),color='blue')